import { useState } from 'react'
import Head from 'next/head'
import Header from './Header/Header'


const Layout = ({children}) => {
  const[accountDropDown,setAccountDropDown] = useState(false)
  const[notifications,setNotification] = useState(false)
  const[messenger,setMessenger] = useState(false)
  
  return (
    <div className='w-full min-h-screen'>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header 
      setAccountDropDown={setAccountDropDown} 
      accountDropDown={accountDropDown}
      notifications={notifications}
      setNotification={setNotification}
      messenger={messenger}
      setMessenger={setMessenger}
    />
    <main className='flex w-full h-screen'>
      {children}
    </main>
  </div>
  )
}

export default Layout